markdown: kramdown
theme: jekyll-theme-cayman
title: MaryEllenTeaches.Me
description: spring, mvc, spring-data-repositories, jpa, mongodb, reactive, rest, docker, jdbc 
site.github.is_project_page: true
